# FILENAME: makefile
# AUTHOR: Zachary Krepelka
# DATE: Wednesday, July 10th, 2024
# ABOUT: a project for the exploration of programming languages
# ORIGIN: https://github.com/zachary-krepelka/ascii-art-fractals.git

java:
	javac Newton.java && java Newton

javascript:
	node newton.js

coffeescript:
	coffee newton.coffee

lua:
	lua newton.lua

python:
	python newton.py

ruby:
	ruby newton.rb

julia:
	julia newton.jl

php:
	php newton.php

kotlin:
	kotlinc newton.kt && kotlin NewtonKt

matlab:
	cmd.exe /c matlab -nojvm -batch newton
